@API_Principal_HostAddress = https://localhost:5001

### GET - Listar todos os produtos
GET {{API_Principal_HostAddress}}/api/produto
Accept: application/json

### GET - Buscar produto por ID
GET {{API_Principal_HostAddress}}/api/produto/1
Accept: application/json

### POST - Criar novo produto
POST {{API_Principal_HostAddress}}/api/produto
Content-Type: application/json

"Notebook Dell"

### PUT - Atualizar produto
PUT {{API_Principal_HostAddress}}/api/produto/1
Content-Type: application/json

"Notebook Dell Atualizado"

### DELETE - Deletar produto
DELETE {{API_Principal_HostAddress}}/api/produto/1
